import { render, screen } from "@testing-library/react";
import MovesDisplay from "./MovesDisplay";
const testData = [
  {
    num: 126,
    accuracy: 85,
    basePower: 110,
    category: "Special",
    name: "Fire Blast",
    pp: 5,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
    },
    secondary: {
      chance: 10,
      status: "brn",
    },
    target: "normal",
    type: "Fire",
    desc: "Has a 10% chance to burn the target.",
    shortDesc: "10% chance to burn the target.",
  },
  {
    num: 248,
    accuracy: 100,
    basePower: 120,
    category: "Special",
    name: "Future Sight",
    pp: 10,
    priority: 0,
    flags: {},
    ignoreImmunity: true,
    isFutureMove: true,
    secondary: null,
    target: "normal",
    type: "Psychic",
    desc: "Deals damage two turns after this move is used. At the end of that turn, the damage is calculated at that time and dealt to the Pokemon at the position the target had when the move was used. If the user is no longer active at the time, damage is calculated based on the user's natural Special Attack stat, types, and level, with no boosts from its held item or Ability. Fails if this move or Doom Desire is already in effect for the target's position.",
    shortDesc: "Hits two turns after being used.",
  },
  {
    num: 473,
    accuracy: 100,
    basePower: 80,
    category: "Special",
    overrideDefensiveStat: "def",
    name: "Psyshock",
    pp: 10,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
    },
    secondary: null,
    target: "normal",
    type: "Psychic",
    desc: "Deals damage to the target based on its Defense instead of Special Defense.",
    shortDesc: "Damages target based on Defense, not Sp. Def.",
  },
  {
    num: 503,
    accuracy: 100,
    basePower: 80,
    category: "Special",
    name: "Scald",
    pp: 15,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
      defrost: 1,
    },
    thawsTarget: true,
    secondary: {
      chance: 30,
      status: "brn",
    },
    target: "normal",
    type: "Water",
    desc: "Has a 30% chance to burn the target. The target thaws out if it is frozen.",
    shortDesc: "30% chance to burn the target. Thaws target.",
  },
  {
    num: 303,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Slack Off",
    pp: 10,
    priority: 0,
    flags: {
      snatch: 1,
      heal: 1,
    },
    heal: [1, 2],
    secondary: null,
    target: "self",
    type: "Normal",
    zMove: {
      effect: "clearnegativeboost",
    },
    desc: "The user restores 1/2 of its maximum HP, rounded half up.",
    shortDesc: "Heals the user by 50% of its max HP.",
  },
  {
    num: 100,
    accuracy: true,
    basePower: 0,
    category: "Status",
    name: "Teleport",
    pp: 20,
    priority: -6,
    flags: {},
    selfSwitch: true,
    secondary: null,
    target: "self",
    type: "Psychic",
    zMove: {
      effect: "heal",
    },
    desc: "If this move is successful and the user has not fainted, the user switches out even if it is trapped and is replaced immediately by a selected party member. The user does not switch out if there are no unfainted party members.",
    shortDesc: "User switches out.",
  },
  {
    num: 92,
    accuracy: 90,
    basePower: 0,
    category: "Status",
    name: "Toxic",
    pp: 10,
    priority: 0,
    flags: {
      protect: 1,
      reflectable: 1,
      mirror: 1,
    },
    status: "tox",
    secondary: null,
    target: "normal",
    type: "Poison",
    zMove: {
      boost: {
        def: 1,
      },
    },
    desc: "Badly poisons the target. If a Poison-type Pokemon uses this move, the target cannot avoid the attack, even if the target is in the middle of a two-turn move.",
    shortDesc: "Badly poisons the target. Poison types can't miss.",
  },
  {
    num: 271,
    accuracy: 100,
    basePower: 0,
    category: "Status",
    name: "Trick",
    pp: 10,
    priority: 0,
    flags: {
      protect: 1,
      mirror: 1,
      allyanim: 1,
    },
    secondary: null,
    target: "normal",
    type: "Psychic",
    zMove: {
      boost: {
        spe: 2,
      },
    },
    desc: "The user swaps its held item with the target's held item. Fails if either the user or the target is holding a Mail or Z-Crystal, if neither is holding an item, if the user is trying to give or take a Mega Stone to or from the species that can Mega Evolve with it, or if the user is trying to give or take a Blue Orb, a Red Orb, a Griseous Orb, a Plate, a Drive, or a Memory to or from a Kyogre, a Groudon, a Giratina, an Arceus, a Genesect, or a Silvally, respectively. The target is immune to this move if it has the Sticky Hold Ability.",
    shortDesc: "User switches its held item with the target's.",
  },
];
describe("MovesDisplay", () => {
  it("moves data displays", () => {
    render(<MovesDisplay movesData={testData} />);
    screen.debug();
    expect(screen.getByText("Moves:")).toBeInTheDocument();
  });
});
